const EVENT_TYPES = {
  CHECKIN: 'CHECKIN',
  CHECKOUT: 'CHECKOUT',
  RESERVATION_CREATED: 'RESERVATION_CREATED',
  RESERVATION_MODIFIED: 'RESERVATION_MODIFIED',
  RESERVATION_CANCELLED: 'RESERVATION_CANCELLED',
  CLEANING_START: 'CLEANING_START',
  CLEANING_END: 'CLEANING_END',
  MAINTENANCE_START: 'MAINTENANCE_START',
  MAINTENANCE_END: 'MAINTENANCE_END',
  OUT_OF_ORDER_START: 'OUT_OF_ORDER_START',
  OUT_OF_ORDER_END: 'OUT_OF_ORDER_END',
  ROOM_BLOCK_START: 'ROOM_BLOCK_START',
  ROOM_BLOCK_END: 'ROOM_BLOCK_END'
};

const EVENT_TYPE_LIST = Object.values(EVENT_TYPES);

module.exports = {
  EVENT_TYPES,
  EVENT_TYPE_LIST
};